USE BaseDeDatos;

DROP TABLE IF EXISTS MessageUser;
DROP TABLE IF EXISTS TablonTargetUser;
DROP TABLE IF EXISTS TablonMessage;
DROP TABLE IF EXISTS TablonUserModerates;
DROP TABLE IF EXISTS UserPermission;

DROP TABLE IF EXISTS Message;
DROP TABLE IF EXISTS Tablon;
DROP TABLE IF EXISTS User;

CREATE TABLE User (
id INT NOT NULL AUTO_INCREMENT,
name VARCHAR(50),
surname1 VARCHAR(50),
surname2 VARCHAR(50),
PRIMARY KEY (id)
) ENGINE=INNODB;


CREATE TABLE Message (
id INT NOT NULL AUTO_INCREMENT,
user_id INT NOT NULL,
message BLOB,
format BINARY,
visibility BINARY,
dateTime TIMESTAMP,
PRIMARY KEY (id),
CONSTRAINT FOREIGN KEY (user_id)
 REFERENCES User (id)
 ON UPDATE CASCADE
 ON DELETE CASCADE
) ENGINE=INNODB;

CREATE TABLE Tablon (
id INT NOT NULL AUTO_INCREMENT,
name VARCHAR(50),
visibility BINARY,
space VARCHAR(50),
PRIMARY KEY (id)
)ENGINE=INNODB;

CREATE TABLE TablonTargetUser (
id INT NOT NULL AUTO_INCREMENT,
tablon_id INT NOT NULL,
user_id INT NOT NULL,
PRIMARY KEY (id),
CONSTRAINT FOREIGN KEY (tablon_id)
 REFERENCES Tablon(id)
 ON UPDATE CASCADE
 ON DELETE CASCADE,
CONSTRAINT FOREIGN KEY (user_id)
 REFERENCES User(id)
 ON UPDATE CASCADE
 ON DELETE CASCADE
) ENGINE=INNODB;

CREATE TABLE TablonMessage (
id INT NOT NULL AUTO_INCREMENT,
tablon_id INT NOT NULL,
message_id INT NOT NULL,
PRIMARY KEY (id),
CONSTRAINT FOREIGN KEY (tablon_id)
 REFERENCES Tablon(id)
 ON UPDATE CASCADE
 ON DELETE CASCADE,
CONSTRAINT FOREIGN KEY (message_id)
 REFERENCES Message(id)
 ON UPDATE CASCADE
 ON DELETE CASCADE
)ENGINE=INNODB;


CREATE TABLE TablonUserModerates (
id INT NOT NULL AUTO_INCREMENT,
tablon_id INT NOT NULL,
user_id INT NOT NULL,
PRIMARY KEY (id),
CONSTRAINT FOREIGN KEY (tablon_id)
 REFERENCES Tablon(id)
 ON UPDATE CASCADE
 ON DELETE CASCADE,
CONSTRAINT FOREIGN KEY (user_id)
 REFERENCES User(id)
 ON UPDATE CASCADE
 ON DELETE CASCADE
)ENGINE=INNODB;



CREATE TABLE UserPermission (
id INT NOT NULL AUTO_INCREMENT,
user_id INT NOT NULL,
tablon_id INT NOT NULL,
permission BINARY NOT NULL,
PRIMARY KEY (id),
CONSTRAINT FOREIGN KEY (user_id)
 REFERENCES User(id)
 ON UPDATE CASCADE
 ON DELETE CASCADE,
CONSTRAINT FOREIGN KEY (tablon_id)
 REFERENCES Tablon(id)
 ON UPDATE CASCADE
 ON DELETE CASCADE
)ENGINE=INNODB;

